### ISSUE TITLE
Do you mind if I write a request to be added to F-Droid?

### ISSUE THREAD

**Issue by Artem13327** [d4rken-org/capod#37]

**Comment by d4rken** [comment]
I don't mind if there is no extra work for me.

Is this the difference between a 3rd party repo and "the default" f-droid repo?

We already have this:
https://apt.izzysoft.de/fdroid/index/apk/eu.darken.capod

/cc @IzzySoft

**Comment by d4rken** [comment]
> Is crowdin-cli.jar needed to build?

No, it's for synchronizing translations.

> What to specify in the field developer 

darken or Matthias Urhahn

> and developer mail?

if it's for admin stuff darken@darken.eu if it's for users support@darken.eu but f-droid users who have issues should go on GitHub, not email me :sweat_smile:.

**Comment by d4rken** [comment]
```yaml
AuthorName: Matthias Urhahn
AuthorEmail: darken@darken.eu
AuthorWebSite: https://darken.eu
Donate: https://github.com/sponsors/d4rken

SourceCode: https://github.com/d4rken-org/capod
IssueTracker: https://github.com/d4rken-org/capod/issues
Changelog: https://github.com/d4rken-org/capod/releases
```

**Comment by licaon-kter** [comment]
@d4rken halp https://gitlab.com/fdroid/rfp/-/issues/2222#note_1116255404

**Comment by d4rken** [comment]
> @d4rken halp https://gitlab.com/fdroid/rfp/-/issues/2222#note_1116255404

I replied there.

> I don't mind if there is no extra work for me.

This already seems to have failed :frowning:

**Comment by Donkey-Doug** [comment]
There currently is no release to download in fdroid. I cannot download this app other than manually downloading github releases.

**Comment by licaon-kter** [comment]
@Donkey-Doug you've seen already that https://gitlab.com/fdroid/rfp/-/issues/2222#note_1116255404 is still open and _not merged_, right?

**Comment by the4anoni** [comment]
For some reason IzzyOnDroid version doesn't install, it requires android.hardware.type.watch.

**Comment by licaon-kter** [comment]
@the4anoni think it's: https://gitlab.com/fdroid/fdroidclient/-/issues/2430 ;(

**Comment by the4anoni** [comment]
> @the4anoni think it's: https://gitlab.com/fdroid/fdroidclient/-/issues/2430 ;(

It actually doesn't install directly from APK.

**Comment by IzzySoft** [comment]
Uh-Oh… Fixed. My updater had grabbed the wrong APK. When I added the app to my repo, there was just a single APK available at each release. Since v2, there are 2 of them attached to `releases/`: one is WEAROS and the other not. The WEAROS one requires `android.hardware.type.watch`, the other does not. I've just told my updater to ignore the WEAROS one and replaced the latest release.

@the4anoni please try again after the next sync today at around 6 pm UTC.

@licaon-kter maybe our recipe needs an update then as well, so we (also) build the other one?

**Comment by licaon-kter** [comment]
@IzzySoft we're not there yet, still waiting for the devs about other issues, afaik

**Comment by the4anoni** [comment]
> Uh-Oh… Fixed. My updater had grabbed the wrong APK. When I added the app to my repo, there was just a single APK available at each release. Since v2, there are 2 of them attached to `releases/`: one is WEAROS and the other not. The WEAROS one requires `android.hardware.type.watch`, the other does not. I've just told my updater to ignore the WEAROS one and replaced the latest release.
> 
> @the4anoni please try again after the next sync today at around 6 pm UTC.
> 
> @licaon-kter maybe our recipe needs an update then as well, so we (also) build the other one?

Now it works as it should :)

**Comment by d4rken** [comment]
Alright, we now have a release script.
Thanks to some [nice scripting work](https://gist.github.com/jv-k/703e79306554c26a65a7cfdb9ca119c6) by @jv-k, I had something to start from, my bash isn't great :face_exhaling:.
It bumps the version, writes it to all necessary places, creates a `VERSION` file that F-Droid can hopefully be setup to parse, and **then** tags the commit and pushes it.

```bash
./release.sh -b -p origin  

Option set: Disable committing to new branch.

Option set: Pushing to <origin>, as the last action in this script.

Current version from <VERSION> file: 2.2.1-rc0

Enter a new version number [2.2.1-rc0]: 

Parsing 2.2.1-rc0

✅  Successfully parsed 2.2.1-rc0 to 2.2.1-rc0
V_MAJOR=2
V_MINOR=2
V_PATCH=1
V_BUILD_TYPE=rc
V_BUILD_COUNTER=0
Setting version to [2.2.1-rc1 (20201010)] ....

––––––

Parsing version.properties:

Found major, replacing: project.versioning.major=2 -> project.versioning.major=2
Found minor, replacing: project.versioning.minor=2 -> project.versioning.minor=2
Found patch, replacing: project.versioning.patch=1 -> project.versioning.patch=1
Found build, replacing: project.versioning.build=0 -> project.versioning.build=1

✅ Updated [version.properties] file

✅ Updated [VERSION] file

Committing...

✅ [main 63f37e5] Release: 2.2.1-rc1
 2 files changed, 2 insertions(+), 2 deletions(-)

✅ Added GIT tag

Pushing files + tags to <origin>...

✅ To github.com:d4rken-org/capod.git
 * [new tag]         v2.2.1-rc1 -> v2.2.1-rc1
To github.com:d4rken-org/capod.git
   01ea08a..63f37e5  main -> main

––––––

✅ Bumped 2.2.1-rc0 –> 2.2.1-rc1

Done 👋🏻
```

**Comment by jv-k** [comment]
I recommend using [ver-bump](https://github.com/jv-k/ver-bump) as a globally installed package, it's superior to that gist that I wrote 🙌🏼

**Comment by d4rken** [comment]
> I recommend using [ver-bump](https://github.com/jv-k/ver-bump) as a globally installed package, it's superior to that gist that I wrote 🙌🏼

I'd still have to modify it too, to fit this use-case. I don't have a package.json that I need to bump but a custom gradle properties file.

**Comment by licaon-kter** [comment]
```
...
> Task :app:packageFossRelease

> Task :app:bugsnagReleaseFoss-releaseTask FAILED
WARNING:API 'ApkVariantOutput.getVersionCodeOverride()' is obsolete and has been replaced with 'VariantOutput.versionCode()'.
It will be removed in version 7.0 of the Android Gradle plugin.
Gradle Properties must be used to change Variant information.
For more information, see https://d.android.com/r/tools/use-properties.
To determine what is calling ApkVariantOutput.getVersionCodeOverride(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING:API 'ApkVariantOutput.getVersionNameOverride()' is obsolete and has been replaced with 'VariantOutput.versionName()'.
It will be removed in version 7.0 of the Android Gradle plugin.
Gradle Properties must be used to change Variant information.
For more information, see https://d.android.com/r/tools/use-properties.
To determine what is calling ApkVariantOutput.getVersionNameOverride(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Bugsnag: Uploading to Releases API
{"errors":["API key not recognised: deadbeef"],"status":"error"}

> Task :app:createFossReleaseApkListingFileRedirect

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bugsnagReleaseFoss-releaseTask'.
> java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Bugsnag request failed to complete
```

What's the plan with bugsnag?

Recipe:
```
  - versionName: 2.7.2-rc0                                                                                                                   
    versionCode: 20702000                                                                                                                    
    commit: 48fd3543e3ca947c06a9b5e805dfeed051538678                                                                                         
    subdir: app                                                                                                                              
    gradle:                                                                                                                                  
      - foss                                                                                                                                 
    rm:                                                                                                                                      
      - crowdin-cli.jar                                                                                                                      
    prebuild:                                                                                                                                
      - cp ../version.properties .                                                                                                           
      - sed -i -e 's/${bugsnagApiKey}/deadbeef/' ../app-wear/src/main/AndroidManifest.xml                                                    
        src/main/AndroidManifest.xml
```
